# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.16.3
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference

      - image: circleci/postgres:12
        environment:
          POSTGRES_USER: giveth_user
          POSTGRES_PASSWORD: mypass
          POSTGRES_DB: giveth
      - image: circleci/redis:6

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install
      - run: npm test
      - deploy:
          name: Production Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
            ssh -o "StrictHostKeyChecking no" givethadmin@serve.giveth.io 'cd impact-graph/ && git checkout develop && git pull && npm ci && npm run serve;'
            fi
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
            ssh -o "StrictHostKeyChecking no" givethadmin@mainnet.serve.giveth.io 'cd impact-graph/ && git checkout master && git pull && npm ci && npm run serve;'
            fi
