name:  CI/CD

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

# I commented the postgres container to reduce time of CI/CD but we can undo that after adding integration tests
#    services:
#      postgres:
#        image: postgres:12
#        env:
#          POSTGRES_USER: giveth_user
#          POSTGRES_PASSWORD: mypass
#          POSTGRES_DB: giveth
#        options: >-
#          --health-cmd pg_isready
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5
#        ports:
#          - 5432:5432
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: install dependencies
        run: npm ci
      - name: run tests
        run: npm run test


